### PR TITLE
Load the assets in assets.chai

### PR DESCRIPTION
**Pull request by RobLoach**
Now running again! Was some small Chai syntax stuff, and moves asset loading to its own file so that it loads correctly.

### CODE REVIEW

**Review by tinglar — CHANGES_REQUESTED** [review]
Oops. I thought that this pull request was the one that was resolved some time ago. I overlooked this one and made a lot of changes since then.

You should look at the current version of main.chai that has (about) all of the intended code, which should give you context on what I meant to do with the code I wrote earlier.

**Comment by tinglar** [comment]
If you are wondering about the emoji/emoticons that I use in my commit messages, I was using this style guide:
https://github.com/slashsBin/styleguide-git-commit-message

I also use this guide:
https://github.com/agis/git-style-guide

**Comment by RobLoach** [comment]
Still erroring out with an incomplete class definition.

**Comment by tinglar** [comment]
:confused: What do you mean? I am still new at ChaiScript.

**Comment by RobLoach** [comment]
```
retroarch -L ~/.config/retroarch/cores/chailove_libretro.so main.chai
[ChaiLove] retro_load_game
[ChaiLove] [libretro] update_variables()
[ChaiLove] Initializing ChaiLove
[ChaiLove] ChaiLove 0.22.2
[ChaiLove] [filesystem] Mounting re-hoard-chailove as /
[ChaiLove] [filesystem] Mounting re-hoard-chailove/ as libretro/system
[ChaiLove] [filesystem] Mounting /home/rob/.config/retroarch/downloads as libretro/assets
[ChaiLove] [filesystem] Mounting re-hoard-chailove/ as libretro/saves
terminate called after throwing an instance of 'chaiscript::exception::eval_error'
  what():  Error: "Incomplete class block" in 'main.chai'  at (194, 20)
[1]    6374 abort (core dumped)  retroarch -L chailove_libretro.so
```

**Comment by RobLoach** [comment]
Two things that would help...

1. Since the script is loaded up before the libraries are available, you'll have to move the Assets loading to its own function called in `def load()`
2. ChaiScript unfortunately doesn't definte and initialize the variables in the same place... You'll have to do something like this...

```


class Player {
	var myVariable
	def Player() {
		this.myVariable = "Something"
	}
}

```

**Review by tinglar — COMMENTED** [review]
These changes look good. I am surprised at how many mistakes I made.

Thank you so much! You were a great help through development here.

**Comment by RobLoach** [comment]
It's still not running, however. Likely some things I changed inadvertently.

**Comment by tinglar** [comment]
…oops. I must have misunderstood what you have written.
Should I revert that commit merge and close this pull request?

**Comment by RobLoach** [comment]
It's okay, don't think I changed that much.

**Comment by tinglar** [comment]
Thank you.

**Comment by tinglar** [comment]
I got a different error now.
https://github.com/tinglar/re-hoard-chailove/issues/3#issuecomment-394914194

**Pull request merged**
